# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90afb4a5ed2e99a9f9bee3640f41589727ba4f8333c5a79c9ad3d1d888de5a465d2a5396cb5d9dcfe81225e60d4ac0b2adde8807df799d313f45adeadb31733a

test:
  secret_key_base: 046b79949711a682fce039d5c4b99fb285235947d52a3f72eafaadd0357a725ea48cd167723899006ecd2aecf0188c23e47088b977fadee8b28b595f71caece9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
